### PR TITLE
Update index.js

### PR DESCRIPTION
**Pull request by davidofug**
1. Moved constant words to top of file.
2. Turn words JSON object into native JS object.
3. Modified translateWord() function //Line 48 and Line 54
4. Removed semi-colons since supported by ES6.

### CODE REVIEW

**Comment by bahiirwa** [comment]
Thanks for the PR. We would want to make the message words dynamic

`function handleMessage(message) {
     if (message.includes(' please')) {`

Please should be a word dynamically inserted from the object.

Also 

` bot.postMessageToChannel( channel, `Please = ${words.please}`, params );`

Both instances of please are still dynamic as the word object provides.

**Comment by davidofug** [comment]
If this works 
`bot.postMessageToChannel( channel,Please = ${words.please}, params );`

We shall be left with solving

`function handleMessage(message) { if (message.includes(' please')) {`

**Comment by bahiirwa** [comment]
This works
bot.postMessageToChannel( channel,Please = ${words.please}, params );

**Comment by davidofug** [comment]
Good you solved it. I had to go the Academy just came back.

**Pull request merged**
